### ISSUE TITLE
complete code and dataset: Microsoft

### ISSUE THREAD

**Issue by fffii** [paper-reproduction/Time-Series_Anomaly_Detection_Service_at_Microsoft#1]
Hello, Jihwan Min
I am very interested about 《Time-Series_Anomaly_Detection_Service_at_Microsoft》，could you upload the complete code of the papper or the dataset Microsoft ? thank you.

**Comment by rpycgo** [comment]
Thank you for your comment.
Unfortunately, I just implemented Spectral Residual part, so I don't have SR-CNN part now.
However, you can take a dataset from [here](https://github.com/iopsai/iops/tree/master/evaluation)

If you have any questions, please feel free to leave comments.
